{{- $priorityClassName := .Values.priorityClass.name | default "paragon-node-exporter-high" }}
{{- if .Values.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ $priorityClassName }}
  labels:
    {{- include "node-exporter.labels" . | nindent 4 }}
value: {{ .Values.priorityClass.value | default 1000000 }}
globalDefault: false
description: {{ .Values.priorityClass.description | default "High priority for Paragon node-exporter DaemonSet" }}
{{- end }} 
