{{/*
Standard ServiceAccount for all microservices.
Call with: include "global.serviceaccount" $ or (dict "root" $ "namespaceTemplate" "service.namespace")
*/}}
{{- define "global.serviceaccount" -}}
{{- $root := . -}}
{{- $namespaceTemplate := "" -}}
{{- if kindIs "map" . -}}
  {{- if hasKey . "root" -}}
    {{- $root = .root -}}
    {{- $namespaceTemplate = .namespaceTemplate | default "" -}}
  {{- end -}}
{{- end -}}
{{- if $root.Values.serviceAccount.create -}}
{{- $name := $root.Chart.Name -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include (printf "%s.serviceAccountName" $name) $root }}
  {{- if $namespaceTemplate }}
  namespace: {{ include $namespaceTemplate $root }}
  {{- end }}
  labels:
    {{- include (printf "%s.labels" $name) $root | nindent 4 }}
  {{- with $root.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}

