{{/*
Standard migration job for microservices with databases.
Call with: include "migration.standard" (dict "root" $ "imageName" "postgres-zeus")
*/}}
{{- define "migration.standard" -}}
{{- $root := .root -}}
{{- $imageName := .imageName -}}
{{- $name := $root.Chart.Name -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrations-{{ $imageName }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      {{- with $root.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include (printf "%s.selectorLabels" $name) $root | nindent 8 }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      securityContext:
        {{- toYaml $root.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $imageName | quote }}
          securityContext:
            {{- toYaml $root.Values.securityContext | nindent 12 }}
          image: "useparagon/{{ $imageName }}:{{ $root.Values.global.paragon_version | default $root.Values.global.env.VERSION }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          resources:
            {{- toYaml $root.Values.resources | nindent 12 }}
          env:
            {{- include "env.standard" $root | nindent 12 }}
      restartPolicy: Never
      {{- with $root.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
