{{/*
Standard Secret for all microservices.
Call with: include "global.secret" $
*/}}
{{- define "global.secret" -}}
{{- if .Values.secrets }}
{{- $name := .Chart.Name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.secretName }}-{{ $.Chart.Name }}
  labels:
    {{- include (printf "%s.labels" $name) . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end -}}

