{{/*
Standard ServiceAccount for all microservices.
Call with: include "global.serviceaccount" $
*/}}
{{- define "global.serviceaccount" -}}
{{- if .Values.serviceAccount.create -}}
{{- $name := .Chart.Name -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include (printf "%s.serviceAccountName" $name) . }}
  labels:
    {{- include (printf "%s.labels" $name) . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}

