{{/*
Standard StatefulSet for services requiring persistent storage.
Call with: include "statefulset.standard" (dict "root" $ "volumeName" "minio" "mountPath" "/var/paragon" "storageSize" "500M")
*/}}
{{- define "statefulset.standard" -}}
{{- $root := .root -}}
{{- $volumeName := .volumeName | default $root.Chart.Name -}}
{{- $mountPath := .mountPath -}}
{{- $storageSize := .storageSize | default "5Gi" -}}
{{- $name := $root.Chart.Name -}}
{{- $command := .command | default "" -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include (printf "%s.fullname" $name) $root }}
  labels:
    {{- include (printf "%s.labels" $name) $root | nindent 4 }}
spec:
  {{- if not $root.Values.autoscaling.enabled }}
  replicas: {{ $root.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include (printf "%s.selectorLabels" $name) $root | nindent 6 }}
  serviceName: {{ include (printf "%s.fullname" $name) $root }}
  template:
    metadata:
      {{- with $root.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include (printf "%s.selectorLabels" $name) $root | nindent 8 }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include (printf "%s.serviceAccountName" $name) $root }}
      securityContext:
        {{- toYaml $root.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $name }}
          securityContext:
            {{- toYaml $root.Values.securityContext | nindent 12 }}
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.global.paragon_version | default $root.Values.image.tag | default $root.Values.global.env.VERSION }}"
          {{- if $command }}
          command: [{{ $command | quote }}]
          {{- end }}
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $root.Values.service.port }}
              protocol: TCP
          lifecycle:
            # need to sleep for `deregistration_delay` + 5s to prevent downtime on deployments
            # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1719#issuecomment-743452334
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 35
          livenessProbe:
            httpGet:
              path: {{ $root.Values.ingress.healthcheck_path | default "/healthz" }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ $root.Values.ingress.readycheck_path | default $root.Values.ingress.healthcheck_path | default "/healthz" }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: {{ $root.Values.ingress.healthcheck_path | default "/healthz" }}
              port: http
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml $root.Values.resources | nindent 12 }}
          env:
            {{- include "env.standard" $root | nindent 12 }}
          volumeMounts:
            - name: {{ $volumeName }}
              mountPath: {{ $mountPath }}
      {{- if and $root.Values.topologySpread $root.Values.topologySpread.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ $root.Values.topologySpread.maxSkew | default 1 }}
          topologyKey: {{ $root.Values.topologySpread.topologyKey | default "kubernetes.io/hostname" }}
          labelSelector:
            matchLabels:
              {{- include (printf "%s.selectorLabels" $name) $root | nindent 14 }}
          whenUnsatisfiable: {{ $root.Values.topologySpread.whenUnsatisfiable | default "ScheduleAnyway" }}
      {{- end }}
      {{- with $root.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ $volumeName }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $storageSize }}
        {{- if eq $root.Values.global.env.HOST_ENV "AWS_K8" }}
        storageClassName: gp3
        {{- end }}
{{- end -}}
