subchart:
  account:
    enabled: true
  cache-replay:
    enabled: false
  cerberus:
    enabled: true
  connect:
    enabled: true
  dashboard:
    enabled: true
  flipt:
    enabled: true
  hades:
    enabled: true
  health-checker:
    enabled: true
  hermes:
    enabled: true
  minio:
    enabled: false
  passport:
    enabled: true
  pheme:
    enabled: true
  release:
    enabled: true
  zeus:
    enabled: true
  worker-actionkit:
    enabled: true
  worker-actions:
    enabled: true
  worker-credentials:
    enabled: true
  worker-crons:
    enabled: true
  worker-deployments:
    enabled: true
  worker-proxy:
    enabled: true
  worker-triggers:
    enabled: true
  worker-workflows:
    enabled: true

restart:
  enabled: true
  schedule: 0 21 * * * # everyday at 1pm PST

global:
  pullPolicy: IfNotPresent
  namespace: paragon
  env: {}
