# .github/workflows/repository-dispatch-listener.yml
name: Update Helm Charts

on:
  repository_dispatch:
    types: [update-charts]

jobs:
  handle-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Store client payload
        env:
          VERSION: ${{ github.event.client_payload.version }}
          PLATFORM_ENV: ${{ github.event.client_payload.platformEnv }}
          GENERATOR_BRANCH: ${{ github.event.client_payload.generatorBranch || 'main' }}
        run: |
          echo "Received Update Charts repository_dispatch event"
          echo "  version: $VERSION"
          echo "  platformEnv: $PLATFORM_ENV"
          echo "  generatorBranch: $GENERATOR_BRANCH"
          echo "  payloadPath: $RUNNER_TEMP/client_payload.json"
          jq <"$GITHUB_EVENT_PATH" '.client_payload' >"$RUNNER_TEMP/client_payload.json"

          echo "Client payload:"
          cat "$RUNNER_TEMP/client_payload.json"
      - name: Checkout generator branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.client_payload.generatorBranch || 'main' }}
      - name: Update Helm Charts
        run: |
          node scripts/update-charts.mjs "$RUNNER_TEMP/client_payload.json" "$GITHUB_WORKSPACE"
      - name: Commit versioned changes
        env:
          VERSION: ${{ github.event.client_payload.version }}
          PLATFORM_ENV: ${{ github.event.client_payload.platformEnv }}
        run: |
          scripts/push-versioned-commit.sh \
            "$VERSION" \
            "$PLATFORM_ENV"
